services:
  postgres:
    image: postgres:17
    container_name: nubank_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5433:5432"
    volumes:
      - nubank_db_data:/var/lib/postgresql/data

volumes:
    nubank_db_data: